package abscence.entite.Seance;
// Generated 26 avr. 2019 22:09:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Seance generated by hbm2java
 */
public class Seance  implements java.io.Serializable {


     private int idSeance;
     private String titre;
     private Date dateDebut;
     private Date dateFin;
     private int identifiantFormateur;

    public Date getDateFin() {
        return dateFin;
    }

    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }
     

    public Seance() {
    }

    public Seance(int idSeance, String titre, Date dateDebut,Date dateFin ,int identifiantFormateur) 
    {
       this.idSeance = idSeance;
       this.titre = titre;
       this.dateDebut = dateDebut;
       this.identifiantFormateur = identifiantFormateur;
       this.dateFin=dateFin;
    }
   
    public int getIdSeance() {
        return this.idSeance;
    }
    
    public void setIdSeance(int idSeance) {
        this.idSeance = idSeance;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateSeance(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public int getIdFormateur() {
        return this.identifiantFormateur;
    }
    
    public void setIdFormateur(int idFormateur) {
        this.identifiantFormateur = idFormateur;
    }




}


