package abscence.entite.ListeAbscence;
// Generated 26 avr. 2019 22:09:06 by Hibernate Tools 4.3.1



/**
 * Listeabscence generated by hbm2java
 */
public class Listeabscence  implements java.io.Serializable {


     private int idListeAbscence;
     private int nbreAbscence;
     private int identifiantFormation;
     private int identifiantApprenant;

    public Listeabscence() {
    }

    public Listeabscence(int idListeAbscence, int nbreAbscence, int idFormation, int idApprenant) {
       this.idListeAbscence = idListeAbscence;
       this.nbreAbscence = nbreAbscence;
       this.identifiantFormation = idFormation;
       this.identifiantApprenant = idApprenant;
    }
   
    public int getIdListeAbscence() {
        return this.idListeAbscence;
    }
    
    public void setIdListeAbscence(int idListeAbscence) {
        this.idListeAbscence = idListeAbscence;
    }
    public int getNbreAbscence() {
        return this.nbreAbscence;
    }
    
    public void setNbreAbscence(int nbreAbscence) {
        this.nbreAbscence = nbreAbscence;
    }
    public int getIdFormation() {
        return this.identifiantFormation;
    }
    
    public void setIdFormation(int idFormation) {
        this.identifiantFormation = idFormation;
    }
    public int getIdApprenant() {
        return this.identifiantApprenant;
    }
    
    public void setIdApprenant(int idApprenant) {
        this.identifiantApprenant = idApprenant;
    }




}


